//titleBarView
export const TAB_TITLE = 'TAB_TITLE';

//drawer Content
export const LOGOUT_DIALOG = 'LOGOUT_DIALOG';

//combineNamesError
export const NAME_ONE_TB_COMBINE = 'NAME_ONE_TB_COMBINE';
export const NAME_TWO_TB_COMBINE = 'NAME_TWO_TB_COMBINE';
export const COMBINE_NAMES_REQUEST = 'COMBINE_NAMES_REQUEST';
export const COMBINE_NAMES_SUCCESS = 'COMBINE_NAMES_SUCCESS';
export const COMBINE_NAMES_ERROR = 'COMBINE_NAMES_ERROR';

//Meaning
export const NAME_MEANING_TEXTBOX = 'NAME_MEANING_TEXTBOX';

//Search
export const SEARCH_TEXT_TEXTBOX = 'SEARCH_TEXT_TEXTBOX';

//Login
export const EMAIL_LOGIN_TEXTBOX = 'EMAIL_LOGIN_TEXTBOX';
export const PASSWORD_LOGIN_TEXTBOX = 'PASSWORD_LOGIN_TEXTBOX';
export const SAVE_LOGIN_DATA_REQUEST = 'SAVE_LOGIN_DATA_REQUEST';
export const SAVE_LOGIN_DATA_SUCCESS_FAILURE_ERROR =
  'SAVE_LOGIN_DATA_SUCCESS_FAILURE_ERROR';

//forgot pass
export const EMAIL_FORGOT_PASS_TEXTBOX = 'EMAIL_FORGOT_PASS_TEXTBOX';
export const SAVE_FORGOT_PASS_DATA_REQUEST = 'SAVE_FORGOT_PASS_DATA_REQUEST';
export const SAVE_FORGOT_PASS_DATA_SUCCESS_FAILURE_ERROR =
  'SAVE_FORGOT_PASS_DATA_SUCCESS_FAILURE_ERROR';

//signup
export const EMAIL_SIGNUP_TEXTBOX = 'EMAIL_SIGNUP_TEXTBOX';
export const FIRST_NAME_SIGNUP_TEXTBOX = 'FIRST_NAME_SIGNUP_TEXTBOX';
export const LAST_NAME_SIGNUP_TEXTBOX = 'LAST_NAME_SIGNUP_TEXTBOX';
export const PASSWORD_SIGNUP_TEXTBOX = 'PASSWORD_SIGNUP_TEXTBOX';
export const SAVE_SIGNUP_DATA_REQUEST = 'SAVE_SIGNUP_DATA_REQUEST';
export const SAVE_SIGNUP_DATA_SUCCESS_FAILURE_ERROR =
  'SAVE_SIGNUP_DATA_SUCCESS_FAILURE_ERROR';

//profile
export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS_FAILURE_ERROR =
  'FETCH_PROFILE_SUCCESS_FAILURE_ERROR';

//editProfile
export const FIRST_NAME_EDIT_PROFILE_TEXTBOX =
  'FIRST_NAME_EDIT_PROFILE_TEXTBOX';
export const LAST_NAME_EDIT_PROFILE_TEXTBOX = 'LAST_NAME_EDIT_PROFILE_TEXTBOX';
export const EMAIL_EDIT_PROFILE_TEXTBOX = 'EMAIL_EDIT_PROFILE_TEXTBOX';
export const PHONE_EDIT_PROFILE_TEXTBOX = 'PHONE_EDIT_PROFILE_TEXTBOX';
export const DOB_EDIT_PROFILE_TEXTBOX = 'DOB_EDIT_PROFILE_TEXTBOX';
export const GENDER_EDIT_PROFILE_TEXTBOX = 'GENDER_EDIT_PROFILE_TEXTBOX';
export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESS_FAILURE_ERROR =
  'EDIT_PROFILE_SUCCESS_FAILURE_ERROR';

//changePassword
export const CURRENT_PASSWORD_CHANGE_PASSWORD_TEXTBOX =
  'CURRENT_PASSWORD_CHANGE_PASSWORD_TEXTBOX';
export const NEW_PASSWORD_CHANGE_PASSWORD_TEXTBOX =
  'NEW_PASSWORD_CHANGE_PASSWORD_TEXTBOX';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS_FAILURE_ERROR =
  'CHANGE_PASSWORD_SUCCESS_FAILURE_ERROR';

//notifications
export const EMAIL_SWITCH_NOTIFICATIONS_TEXTBOX =
  'EMAIL_SWITCH_NOTIFICATIONS_TEXTBOX';
export const NOTIFICATION_SWITCH_NOTIFICATIONS_TEXTBOX =
  'NOTIFICATION_SWITCH_NOTIFICATIONS_TEXTBOX';
export const MESSAGE_SWITCH_NOTIFICATIONS_TEXTBOX =
  'MESSAGE_SWITCH_NOTIFICATIONS_TEXTBOX';
export const PHONE_SWITCH_NOTIFICATIONS_TEXTBOX =
  'PHONE_SWITCH_NOTIFICATIONS_TEXTBOX';
export const SAVE_NOTIFICATIONS_SETTINGS_REQUEST =
  'SAVE_NOTIFICATIONS_SETTINGS_REQUEST';
export const SAVE_NOTIFICATIONS_SETTING_SUCCESS_FAILURE_ERROR =
  'SAVE_NOTIFICATIONS_SETTING_SUCCESS_FAILURE_ERROR';

//appsettings
export const APP_SETTINGS_REQUEST = 'APP_SETTINGS_REQUEST';
export const APP_SETTINGS_SUCCESS_FAILURE_ERROR =
  'APP_SETTINGS_SUCCESS_FAILURE_ERROR';

//filter
export const SURNAME_FILTER_TEXTBOX = 'SURNAME_FILTER_TEXTBOX';
export const APPLY_FILTER_REQUEST = 'APPLY_FILTER_REQUEST';
export const APPLY_FILTER_SUCCESS_FAILURE_ERROR =
  'APPLY_FILTER_SUCCESS_FAILURE_ERROR';
